### ISSUE TITLE
Base URI fixup

### ISSUE THREAD

**Issue by dmj** [Schematron/schematron-enhancement-proposals#2]
Schematron allows for the inclusion of external definitions via sch:include (5.4.4) and sch:expand (5.4.3). The Schematron specification does not discuss how this inclusion effects relative URI references in the inserted content.

A processor implementing this proposal performs base URI fixup as defined in section 4.5.5 of [XINCLUDE].

[XINCLUDE] XML Inclusions (XInclude) Version 1.0 (Second Edition), https://www.w3.org/TR/xinclude/

**Comment by dmj** [comment]
See https://github.com/schxslt/schxslt/pull/176 and https://github.com/schxslt/schxslt/issues/178

**Comment by AndrewSales** [comment]
Added a new clause under "6 Semantics".
