### ISSUE TITLE
Remove deprecated query language bindings

### ISSUE THREAD

**Issue by xatapult** [Schematron/schematron-enhancement-proposals#26]
There are several query language bindings defined that can be considered deprecated:

* `stx`: The STX initiative never came beyond the “working draft” stage. Its last update was in April 2007. Its ideas found their way into XSLT 3.0.
* `exslt`: EXSLT can be considered outdated (the last change is from 2003). Most if not all of its proposed extensions have found their way into the newer XPath versions.

My proposal would be to remove these bindings from the standard.

**Comment by rjelliffe** [comment]
+1

**Comment by AndrewSales** [comment]
Removed from latest draft.
