### ISSUE TITLE
Error in ISO 2020, section 5.4.3 (assert) and 5.4.12 (report)

### ISSUE THREAD

**Issue by dmj** [Schematron/schematron-enhancement-proposals#36]
Sections 5.4.3 and 5.4.12 fail to mention the @properties attribute on a assert or report element.

**Comment by AndrewSales** [comment]
(I kept reading the title as a reference to another ISO standard.)

**Comment by AndrewSales** [comment]
Indeed, the `properties` attribute is not covered in clause 5.5 either. The intention as the text stands seems to be that Annex N (informative) demonstrates the use of properties by examples. By analogy, the `diagnostics` attribute isn't mentioned in its own right either (i.e. as a sub-clause), but is mentioned under element `diagnostic`, so for consistency we should probably give attribute `properties` similar treatment.

**Comment by AndrewSales** [comment]
> Sections 5.4.3 and 5.4.12 fail to mention the @properties attribute on a assert or report element.

They do now.

**Comment by AndrewSales** [comment]
`diagnostics` and `properties` attributes also now covered in clause 5.5.
