### ISSUE TITLE
Allow name and value-of to be nested in emph, dir, and span

### ISSUE THREAD

**Issue by dmj** [Schematron/schematron-enhancement-proposals#37]
Schematron defines a simple templating language for messages. The normative grammar disallows value-of and name to be nested in a span, emph, or dir. This makes it impossible to emphasize or mark a part of the message with a dynamically calculated value.

The grammar should be changed to allow value-of and name inside span, emph, and dir.

**Comment by AndrewSales** [comment]
Schema updated - any reason not to allow `foreign` in `emph`?
see https://github.com/Schematron/schema/commit/7b967bcb272143e09f9f90f8ad3de46eb8992082#diff-9202b75b42b32283bb7212d62805a7e9f1f5b40b7c3b322a3ad20d7dd9bf0111R73

**Comment by dmj** [comment]
I can't think of a reason. So ```foreign``` in ```emph``` it is.
