### ISSUE TITLE
Fix errors in Schematron for SVRL

### ISSUE THREAD

**Issue by tgraham-antenna** [Schematron/schematron-enhancement-proposals#38]
Schematron/schema#6 proposes several fixes to the Schematron for SVRL:
- 'second-level' rule checked for sibling, not parent
- 'svrl:schematron-output' rule checked that the current element did not exist
- 'svrl:schematron-output' rule failed to count a child element type
- 'svrl:fired-rule' rule omitted namespace when checking for a preceding sibling element

If the fixes are correct, they should be included in the next version of Schematron (or, as an exercise for the editor, implemented as changes in the current Schematron written for the `xslt` binding).

**Comment by AndrewSales** [comment]
@tgraham-antenna 's PR merged in via https://github.com/Schematron/schema/commit/d00f83aa3c7d3008ead41088cf23b5786ae39725, so closing.
