### ISSUE TITLE
05.03 Whitespace [ref. JP19 021]

### ISSUE THREAD

**Issue by AndrewSales** [Schematron/schematron-enhancement-proposals#54]
Whitespace is already defined by XML 1.0.	We propose to drop this subclause.

**Comment by AndrewSales** [comment]
Proposal to remove added to current draft.

**Comment by rjelliffe** [comment]
This thread is entirely cryptic.

It seems to be about some words in a text we have no access to (unless we
pay several hundred dollars) at a location that is not specified, and
perhaps in response to a comment we have no access to and is not summarized
for us. And then, without any discussion, an answer is declared.

**Comment by AndrewSales** [comment]
@rjelliffe there were four defects reported by national bodies during the drafting of the 2020 edition which the WG at the time accepted, but agreed to defer until the next revision. So the decision to accept these defects was already made in 2019, and the current WG constituted on the basis that its work would include addressing outstanding defects previously raised.

I have raised them as issues here in order to keep track of them. I'm sorry if this confused anyone.
You have also commented on the three others - thank you. 

This one refers to clause 5.3 in the 2020 edition, which defines whitespace. The proposal to remove the clause has now been made and may still be reversed by the WG.

The fact that the standard ISO is revising is no longer publicly available is regrettable, as has been discussed at length, but that is the situation.

The standard is being actively developed by ISO again and WG 10 maintains it. Discussion here is welcome and has been encouraged since the last edition, in part to promote community engagement. But equally the ISO process is what it is.
