### ISSUE TITLE
pattern/@documents: rules apply only to subordinate documents?

### ISSUE THREAD

**Issue by AndrewSales** [Schematron/schematron-enhancement-proposals#59]
I'm assuming the rules in a `pattern[@documents]` apply only to those subordinate documents retrieved, and not also to the instance document.

**Comment by xatapult** [comment]
At this moment, it is.

**Comment by AndrewSales** [comment]
It would be worth making this explicit in the text of the standard either way.

**Comment by AndrewSales** [comment]
Added a note that this is the case.
